import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken';
import dns from 'node:dns';
import fs from 'node:fs'; import path from 'node:path'; import multer from 'multer';
import { User, DoctorProfile, Slot, Appointment, HealthRecord, Reminder, Leave, Department, Prescription, SymptomAssessment, Notification, Dispute, DemoState } from './models.js';
import { recommendSpecialty } from './symptom-model.js';
// Atlas uses DNS SRV records. A public resolver avoids local DNS policies that block SRV lookups.
dns.setServers((process.env.DNS_SERVERS || '1.1.1.1,8.8.8.8').split(','));
const app = express(), port = process.env.PORT || 8000;
const allowedOrigins = (process.env.CLIENT_ORIGIN || 'http://localhost:5173,http://127.0.0.1:5173').split(',').map(origin => origin.trim()).filter(Boolean);
if (!process.env.MONGODB_URI || !process.env.JWT_SECRET) throw new Error('Create .env from .env.example and set MONGODB_URI and JWT_SECRET.');
await mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 8000, family: 4 }); console.log('MongoDB connected');
app.use(cors({ origin(origin, done) { if (!origin || allowedOrigins.includes(origin)) return done(null, true); return done(new Error('Origin not allowed by CORS')); } })); app.use(express.json());
const uploadDir=path.resolve('uploads');fs.mkdirSync(uploadDir,{recursive:true});const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(_req,file,done)=>done(null,`${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`)}),limits:{fileSize:5*1024*1024},fileFilter:(_req,file,done)=>done(null,['application/pdf','image/jpeg','image/png'].includes(file.mimetype))});app.use('/uploads',express.static(uploadDir));
app.get('/api/health', (_req, res) => res.json({ status: 'ok', database: mongoose.connection.name }));
app.get('/api', (_req, res) => res.json({ name: 'CareFlow API', status: 'running', health: '/api/health' }));
// Local demonstration bridge: the React prototype persists its complete demo state in MongoDB.
// Production features should use the authenticated, normalized endpoints below instead.
app.get('/api/demo-state', async (_req, res) => { const record = await DemoState.findOne({ key: 'primary' }).lean(); const state = record?.state?.users?.length ? record.state : null; res.json({ state }); });
app.put('/api/demo-state', async (req, res) => { if (!req.body?.state || typeof req.body.state !== 'object') return res.status(400).json({ error: 'A state object is required' }); await DemoState.findOneAndUpdate({ key: 'primary' }, { state: req.body.state }, { upsert: true, returnDocument: 'after' }); res.json({ saved: true }); });
const safeUser = u => ({ id: u._id, fullName: u.fullName, email: u.email, role: u.role, age: u.age, bloodGroup: u.bloodGroup, allergies: u.allergies, chronicConditions: u.chronicConditions });
const token = u => jwt.sign({ sub: u._id.toString(), role: u.role }, process.env.JWT_SECRET, { expiresIn: '1h' });
const auth = (...roles) => async (req,res,next) => { try { const raw=req.headers.authorization?.replace('Bearer ',''); const payload=jwt.verify(raw,process.env.JWT_SECRET); req.user=await User.findById(payload.sub); if(!req.user || (roles.length && !roles.includes(req.user.role))) return res.status(403).json({error:'Permission denied'}); next(); } catch { res.status(401).json({error:'Authentication required'}); } };
const offlineReportAnalysis = reportText => ({ summary: 'Basic offline summary: the report text was saved for clinical review. Gemini analysis is temporarily unavailable.', extractedItems: reportText.split(/\n|,/).map(item=>item.trim()).filter(Boolean).slice(0,6).map(item=>({name:'Report item',displayedValue:item})), questionsForClinician: ['Which results should I discuss with my clinician?', 'Are any follow-up tests or visits needed?'], safetyNote: 'This offline summary is informational only. Please review the report with a qualified clinician.' });
const localAiFallback = (instruction, input) => instruction.includes('healthcare navigation assistant') ? recommendSpecialty(input) : offlineReportAnalysis(input);
const geminiJson = async (instruction, input) => {
  if (!process.env.GEMINI_API_KEY) {
    return localAiFallback(instruction, input);
  }
  const model = process.env.GEMINI_MODEL || 'gemini-3.6-flash';
  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${process.env.GEMINI_API_KEY}`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ systemInstruction: { parts: [{ text: instruction }] }, contents: [{ role: 'user', parts: [{ text: input }] }], generationConfig: { responseMimeType: 'application/json', temperature: 0.2 } }),
  });
  if (!response.ok) return localAiFallback(instruction, input);
  const body = await response.json();
  const text = body.candidates?.[0]?.content?.parts?.map(part => part.text || '').join('') || '{}';
  return JSON.parse(text);
};
const sendEmail = async ({to,subject,text}) => { if(!process.env.BREVO_API_KEY||!to)return false; const response=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'Content-Type':'application/json','api-key':process.env.BREVO_API_KEY},body:JSON.stringify({sender:{email:process.env.BREVO_SENDER_EMAIL||'no-reply@example.com',name:process.env.BREVO_SENDER_NAME||'CareFlow'},to:[{email:to}],subject,textContent:text})}); if(!response.ok)throw new Error('Brevo email request failed'); return true; };
const queuePrediction = async doctorId => { const completed=await Appointment.find({doctor:doctorId,status:'completed',consultationDurationMinutes:{$gt:0}}).select('queuePosition consultationDurationMinutes'); const active=await Appointment.countDocuments({doctor:doctorId,status:{$in:['confirmed','in_progress']},emergency:false}); if(completed.length<2)return {queuePosition:active,predictedWaitMinutes:active*18}; const meanX=completed.reduce((sum,row)=>sum+(row.queuePosition||0),0)/completed.length,meanY=completed.reduce((sum,row)=>sum+row.consultationDurationMinutes,0)/completed.length; const denominator=completed.reduce((sum,row)=>sum+((row.queuePosition||0)-meanX)**2,0); const slope=denominator?completed.reduce((sum,row)=>sum+((row.queuePosition||0)-meanX)*(row.consultationDurationMinutes-meanY),0)/denominator:0; const duration=Math.max(8,Math.min(45,meanY+slope*(active-meanX))); return {queuePosition:active,predictedWaitMinutes:Math.round(active*duration)}; };
app.post('/api/auth/register', async (req,res) => { const { fullName,email,password,role='patient',specialty='General Medicine',fee=0,experienceYears=0,...profile }=req.body; if(!['patient','doctor'].includes(role)||!password||password.length<8) return res.status(400).json({error:'Use a patient/doctor role and password of 8+ characters'}); if(await User.exists({email:email?.toLowerCase()})) return res.status(409).json({error:'Email already exists'}); const user=await User.create({fullName,email,passwordHash:await bcrypt.hash(password,12),role,...profile}); if(role==='doctor') await DoctorProfile.create({user:user._id,specialty,fee,experienceYears,approved:false}); res.status(201).json({token:token(user),user:safeUser(user)}); });
app.post('/api/auth/login', async (req,res) => { const u=await User.findOne({email:req.body.email?.toLowerCase()}); if(!u||!await bcrypt.compare(req.body.password||'',u.passwordHash)) return res.status(401).json({error:'Incorrect email or password'}); res.json({token:token(u),user:safeUser(u)}); });
app.post('/api/auth/password-reset/request',async(req,res)=>{const user=await User.findOne({email:req.body.email?.toLowerCase()});if(!user)return res.json({message:'If an account exists, a reset code has been sent.'});const code=String(Math.floor(100000+Math.random()*900000));user.passwordResetCodeHash=await bcrypt.hash(code,10);user.passwordResetExpiresAt=new Date(Date.now()+15*60*1000);await user.save();let emailed=false;try{emailed=await sendEmail({to:user.email,subject:'CareFlow password reset code',text:`Your CareFlow password reset code is ${code}. It expires in 15 minutes.`})}catch{}console.log(`CareFlow password-reset code for ${user.email}: ${code}`);res.json({message:emailed?'Reset code sent to your email.':'Reset code created. For this final-year demo, retrieve it from the API server terminal.',developmentCode:process.env.NODE_ENV==='production'?undefined:code});});
app.post('/api/auth/password-reset/confirm',async(req,res)=>{const {email,code,newPassword}=req.body;if(!newPassword||newPassword.length<8)return res.status(400).json({error:'Use a password with at least 8 characters'});const user=await User.findOne({email:email?.toLowerCase(),passwordResetExpiresAt:{$gt:new Date()}});if(!user||!await bcrypt.compare(String(code||''),user.passwordResetCodeHash||''))return res.status(400).json({error:'Invalid or expired reset code'});user.passwordHash=await bcrypt.hash(newPassword,12);user.passwordResetCodeHash=undefined;user.passwordResetExpiresAt=undefined;await user.save();res.json({message:'Password reset completed'});});
app.get('/api/me',auth(),(req,res)=>res.json(safeUser(req.user)));
app.patch('/api/me',auth(),async(req,res)=>{const allowed=['fullName','age','bloodGroup','allergies','chronicConditions'];for(const key of allowed)if(req.body[key]!==undefined)req.user[key]=req.body[key];await req.user.save();res.json(safeUser(req.user));});
app.get('/api/doctors', async (_req,res) => { const rows=await DoctorProfile.find({approved:true}).populate('user','fullName'); res.json(rows.map(x=>({id:x.user._id,name:x.user.fullName,specialty:x.specialty,experienceYears:x.experienceYears,fee:x.fee}))); });
app.post('/api/doctors/profile',auth('doctor'),async(req,res)=>res.status(201).json(await DoctorProfile.findOneAndUpdate({user:req.user._id},{...req.body,user:req.user._id},{new:true,upsert:true})));
app.post('/api/slots',auth('doctor'),async(req,res)=>{ if(!await DoctorProfile.exists({user:req.user._id,approved:true})) return res.status(403).json({error:'Doctor approval is required before managing availability'}); try { res.status(201).json(await Slot.create({doctor:req.user._id,...req.body})); } catch {res.status(409).json({error:'This time slot already exists'});} });
app.get('/api/slots/mine',auth('doctor'),async(req,res)=>res.json(await Slot.find({doctor:req.user._id}).sort('startsAt')));
app.patch('/api/slots/:id',auth('doctor'),async(req,res)=>{const slot=await Slot.findOneAndUpdate({_id:req.params.id,doctor:req.user._id,booked:false},{unavailable:!!req.body.unavailable},{new:true});if(!slot)return res.status(404).json({error:'Available slot not found'});res.json(slot);});
app.delete('/api/slots/:id',auth('doctor'),async(req,res)=>{const slot=await Slot.findOneAndDelete({_id:req.params.id,doctor:req.user._id,booked:false});if(!slot)return res.status(409).json({error:'Only unbooked slots can be removed'});res.status(204).end();});
app.get('/api/doctors/:id/leaves',async(req,res)=>res.json(await Leave.find({doctor:req.params.id}).sort('date')));
app.get('/api/leaves/mine',auth('doctor'),async(req,res)=>res.json(await Leave.find({doctor:req.user._id}).sort('date')));
app.post('/api/leaves',auth('doctor'),async(req,res)=>{const date=String(req.body.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({error:'Use a valid leave date'});try{await Slot.updateMany({doctor:req.user._id,booked:false,startsAt:{$gte:new Date(`${date}T00:00:00`),$lt:new Date(`${date}T23:59:59.999`)}},{$set:{unavailable:true}});res.status(201).json(await Leave.create({doctor:req.user._id,date,reason:req.body.reason||''}));}catch{return res.status(409).json({error:'Leave is already recorded for this date'});}});
app.delete('/api/leaves/:id',auth('doctor'),async(req,res)=>{const leave=await Leave.findOneAndDelete({_id:req.params.id,doctor:req.user._id});if(!leave)return res.status(404).json({error:'Leave not found'});await Slot.updateMany({doctor:req.user._id,booked:false,startsAt:{$gte:new Date(`${leave.date}T00:00:00`),$lt:new Date(`${leave.date}T23:59:59.999`)}},{$set:{unavailable:false}});res.status(204).end();});
app.get('/api/doctors/:id/slots',async(req,res)=>res.json(await Slot.find({doctor:req.params.id,booked:false,unavailable:{$ne:true},startsAt:{$gte:new Date()}}).sort('startsAt')));
app.post('/api/appointments',auth('patient'),async(req,res)=>{ const {doctorId,slotId,emergency=false}=req.body; if(!await DoctorProfile.exists({user:doctorId,approved:true}))return res.status(400).json({error:'Doctor is unavailable for booking'}); const slot=await Slot.findOneAndUpdate({_id:slotId,doctor:doctorId,booked:false},{$set:{booked:true}},{new:true}); if(!slot) return res.status(409).json({error:'Slot is unavailable. Please choose another.'}); const prediction=emergency?{queuePosition:0,predictedWaitMinutes:5}:await queuePrediction(doctorId); const appt=await Appointment.create({patient:req.user._id,doctor:doctorId,slot:slot._id,emergency,...prediction}); const body=`Your appointment is confirmed. Estimated wait: ${appt.predictedWaitMinutes} minutes.`; await Notification.create({user:req.user._id,title:'Appointment confirmed',body,type:'appointment'}); try{await sendEmail({to:req.user.email,subject:'CareFlow appointment confirmed',text:body})}catch{} res.status(201).json(appt); });
app.get('/api/appointments/mine',auth(),async(req,res)=>res.json(await Appointment.find(req.user.role==='patient'?{patient:req.user._id}:{doctor:req.user._id}).populate('doctor','fullName').populate('patient','fullName').populate('slot').sort('-createdAt')));
app.patch('/api/appointments/:id/status',auth('doctor','admin'),async(req,res)=>{const allowed=['confirmed','in_progress','completed','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});const appt=await Appointment.findById(req.params.id);if(!appt||(req.user.role==='doctor'&&appt.doctor.toString()!==req.user.id))return res.status(404).json({error:'Appointment not found'});appt.status=req.body.status;if(req.body.consultationDurationMinutes!==undefined)appt.consultationDurationMinutes=Math.max(1,Math.min(240,Number(req.body.consultationDurationMinutes)));await appt.save();if(req.body.status==='cancelled')await Slot.findByIdAndUpdate(appt.slot,{booked:false});await Notification.create({user:appt.patient,title:`Appointment ${req.body.status}`,body:`Your appointment status was updated to ${req.body.status}.`,type:'appointment'});res.json(appt);});
app.patch('/api/appointments/:id/cancel',auth('patient'),async(req,res)=>{const appt=await Appointment.findOne({_id:req.params.id,patient:req.user._id});if(!appt||appt.status!=='confirmed')return res.status(404).json({error:'Confirmed appointment not found'});appt.status='cancelled';await appt.save();await Slot.findByIdAndUpdate(appt.slot,{booked:false});res.json(appt);});
const hasCareRelationship=async(doctorId,patientId)=>Boolean(await Appointment.exists({doctor:doctorId,patient:patientId,status:{$ne:'cancelled'}}));
app.get('/api/records/:patientId',auth(),async(req,res)=>{if(req.user.role==='patient'&&req.user.id!==req.params.patientId)return res.status(403).json({error:'Own records only'});if(req.user.role==='doctor'&&!await hasCareRelationship(req.user._id,req.params.patientId))return res.status(403).json({error:'A current or completed appointment is required to view this patient history'});res.json(await HealthRecord.find({patient:req.params.patientId}).sort('-createdAt'));});
app.post('/api/records',auth('doctor','admin'),async(req,res)=>res.status(201).json(await HealthRecord.create({...req.body,doctor:req.user.role==='doctor'?req.user._id:null})));
app.post('/api/records/upload',auth('patient','doctor','admin'),upload.single('report'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Upload a PDF, PNG, or JPG report under 5 MB'});const patient=req.user.role==='patient'?req.user._id:req.body.patientId;if(!patient)return res.status(400).json({error:'Patient is required'});const record=await HealthRecord.create({patient,doctor:req.user.role==='doctor'?req.user._id:null,category:'lab_report',title:req.body.title||req.file.originalname,content:req.body.description||'Uploaded lab report.',attachmentUrl:`/uploads/${req.file.filename}`});res.status(201).json(record);});
app.get('/api/reminders/mine',auth('patient'),async(req,res)=>res.json(await Reminder.find({patient:req.user._id,active:true})));
app.post('/api/reminders',auth('patient','doctor'),async(req,res)=>res.status(201).json(await Reminder.create(req.body)));
app.get('/api/prescriptions/:patientId',auth(),async(req,res)=>{if(req.user.role==='patient'&&req.user.id!==req.params.patientId)return res.status(403).json({error:'Own prescriptions only'});if(req.user.role==='doctor'&&!await hasCareRelationship(req.user._id,req.params.patientId))return res.status(403).json({error:'A current or completed appointment is required to view prescriptions'});res.json(await Prescription.find({patient:req.params.patientId}).sort('-createdAt'));});
app.post('/api/prescriptions',auth('doctor'),async(req,res)=>{if(!await hasCareRelationship(req.user._id,req.body.patient))return res.status(403).json({error:'Create a prescription only for an assigned patient'});const prescription=await Prescription.create({...req.body,doctor:req.user._id});for(const med of prescription.medicines){if(med.schedule)await Reminder.create({patient:prescription.patient,prescription:prescription._id,medicine:med.name,dose:med.dose,reminderTime:med.schedule});}const body='Your doctor added a prescription and medicine reminders.';await Notification.create({user:prescription.patient,title:'New prescription',body,type:'prescription'});try{const patient=await User.findById(prescription.patient);await sendEmail({to:patient?.email,subject:'CareFlow new prescription',text:body})}catch{}res.status(201).json(prescription);});
app.patch('/api/prescriptions/:id/discontinue',auth('doctor'),async(req,res)=>{const prescription=await Prescription.findOne({_id:req.params.id,doctor:req.user._id});if(!prescription)return res.status(404).json({error:'Prescription not found'});prescription.status='discontinued';prescription.discontinuedAt=new Date();await prescription.save();await Reminder.updateMany({prescription:prescription._id},{$set:{active:false}});await Notification.create({user:prescription.patient,title:'Medicine discontinued',body:'A doctor discontinued a medicine. Its reminder has been stopped; the prescription remains in your medical history.',type:'prescription'});res.json(prescription);});
app.get('/api/notifications/mine',auth(),async(req,res)=>res.json(await Notification.find({user:req.user._id}).sort('-createdAt').limit(30)));
app.post('/api/notifications/reminder-email',auth('doctor'),async(req,res)=>{const patient=await User.findOne({email:req.body.patientEmail?.toLowerCase(),role:'patient'});if(!patient)return res.status(404).json({error:'Patient email not found'});const medicine=String(req.body.medicine||'').trim(),time=String(req.body.time||'').trim();if(!medicine||!time)return res.status(400).json({error:'Medicine and reminder time are required'});const body=`Your doctor prescribed ${medicine}. Reminder time: ${time}. Follow the prescribed instructions.`;try{await sendEmail({to:patient.email,subject:'CareFlow medicine reminder',text:body});await Notification.create({user:patient._id,title:'Medicine reminder sent',body,type:'reminder'});res.json({sent:true});}catch{res.status(503).json({error:'Email delivery is not configured. Add Brevo settings to .env.'})}});
app.post('/api/symptoms/recommend',auth('patient'),async(req,res)=>{ try { const symptoms=String(req.body.symptoms||'').trim(); if(!symptoms) return res.status(400).json({error:'Symptoms are required'}); const data=await geminiJson('You are a healthcare navigation assistant. Never diagnose, name diseases, estimate severity, prescribe, or give treatment. Return only JSON with recommendedSpecialty and message. If emergency warning signs may be present, recommendedSpecialty must be "Emergency care" and message must tell the user to seek emergency services now.',symptoms); const recommendedSpecialty=data.recommendedSpecialty||'General Medicine',message=data.message||'Please start with a general physician for an appropriate assessment.'; await SymptomAssessment.create({patient:req.user._id,symptoms,recommendedSpecialty,message,provider:'gemini'}); res.json({recommendedSpecialty,message,disclaimer:'Specialty recommendation only — not a diagnosis. Seek emergency help for severe or life-threatening symptoms.'}); } catch (error) { res.status(503).json({error:error.message==='Gemini is not configured'?'Symptom service is not configured':'Specialty recommendation service is unavailable'}); } });
app.post('/api/reports/analyze',auth('patient','doctor','admin'),async(req,res)=>{ try { const reportText=String(req.body.reportText||'').trim(); if(reportText.length<10) return res.status(400).json({error:'Provide at least 10 characters of report text'}); if(reportText.length>12000) return res.status(400).json({error:'Report text must be 12,000 characters or less'}); const data=await geminiJson('You summarize health-report text for a patient portal. Never diagnose, prescribe, interpret results as normal or abnormal, assign severity, or replace a clinician. Return only JSON with summary (plain-language short summary), extractedItems (array of objects with name and displayedValue copied from input where possible), questionsForClinician (array of up to 4 neutral questions), and safetyNote (one sentence telling the user to consult a qualified clinician).',reportText); res.json({summary:data.summary||'No summary was generated.',extractedItems:Array.isArray(data.extractedItems)?data.extractedItems:[],questionsForClinician:Array.isArray(data.questionsForClinician)?data.questionsForClinician:[],safetyNote:data.safetyNote||'This is informational only. Please review your report with a qualified clinician.'}); } catch (error) { res.status(503).json({error:error.message==='Gemini is not configured'?'Report analysis service is not configured':'Report analysis service is unavailable'}); } });
app.get('/api/departments',async(_req,res)=>res.json(await Department.find({active:true}).sort('name')));
app.post('/api/departments',auth('admin'),async(req,res)=>res.status(201).json(await Department.create(req.body)));
app.patch('/api/departments/:id',auth('admin'),async(req,res)=>res.json(await Department.findByIdAndUpdate(req.params.id,req.body,{new:true})));
app.get('/api/admin/analytics',auth('admin'),async(_req,res)=>res.json({patients:await User.countDocuments({role:'patient'}),doctors:await User.countDocuments({role:'doctor'}),appointments:await Appointment.countDocuments(),pendingDoctors:await DoctorProfile.countDocuments({approved:false}),appointmentsByDay:await Appointment.aggregate([{$group:{_id:{$dateToString:{format:'%a',date:'$createdAt'}},count:{$sum:1}}}])}));
app.get('/api/admin/pending-doctors',auth('admin'),async(_req,res)=>res.json(await DoctorProfile.find({approved:false}).populate('user','fullName email')));
app.patch('/api/admin/doctors/:id',auth('admin'),async(req,res)=>res.json(await DoctorProfile.findOneAndUpdate({user:req.params.id},{approved:!!req.body.approved},{new:true})));
app.delete('/api/admin/doctors/:id',auth('admin'),async(req,res)=>{const profile=await DoctorProfile.findOneAndDelete({user:req.params.id,approved:false});if(!profile)return res.status(404).json({error:'Pending doctor not found'});await User.findByIdAndDelete(req.params.id);res.status(204).end();});
app.post('/api/disputes',auth('patient'),async(req,res)=>{const title=String(req.body.title||'').trim();if(!title)return res.status(400).json({error:'Dispute title is required'});const dispute=await Dispute.create({patient:req.user._id,appointment:req.body.appointment||undefined,title,description:req.body.description||''});res.status(201).json(dispute);});
app.get('/api/disputes/mine',auth('patient'),async(req,res)=>res.json(await Dispute.find({patient:req.user._id}).sort('-createdAt')));
app.get('/api/admin/disputes',auth('admin'),async(_req,res)=>res.json(await Dispute.find().populate('patient','fullName email').populate('appointment').sort('-createdAt')));
app.patch('/api/admin/disputes/:id',auth('admin'),async(req,res)=>{const allowed=['open','in_review','resolved','rejected'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid dispute status'});const dispute=await Dispute.findByIdAndUpdate(req.params.id,{status:req.body.status,resolutionNote:req.body.resolutionNote||''},{new:true});if(!dispute)return res.status(404).json({error:'Dispute not found'});res.json(dispute);});
app.get('/api/admin/reports/appointments.csv',auth('admin'),async(_req,res)=>{const rows=await Appointment.find().populate('patient','fullName email').populate('doctor','fullName').populate('slot','startsAt').sort('-createdAt');const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv=['Patient,Email,Doctor,Appointment time,Status,Emergency,Predicted wait minutes',...rows.map(a=>[a.patient?.fullName,a.patient?.email,a.doctor?.fullName,a.slot?.startsAt?.toISOString(),a.status,a.emergency,a.predictedWaitMinutes].map(esc).join(','))].join('\n');res.header('Content-Type','text/csv').attachment('careflow-appointments.csv').send(csv);});
app.listen(port,()=>console.log(`CareFlow API listening on http://localhost:${port}`));
