import {useEffect,useState} from 'react';
import {Bar,Doughnut} from 'react-chartjs-2';
import {Chart as ChartJS,ArcElement,BarElement,CategoryScale,Legend,LinearScale,Tooltip} from 'chart.js';
import * as I from 'lucide-react';

ChartJS.register(ArcElement,BarElement,CategoryScale,Legend,LinearScale,Tooltip);
const API=import.meta.env.VITE_API_URL||'http://localhost:8012/api';
const fmt=value=>value?new Date(value).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'—';
const request=async(path,options={})=>{const token=sessionStorage.getItem('careflow_token');const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});if(response.status===204)return null;const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data};
const Button=({children,...props})=><button className="primary" {...props}>{children}</button>;

export function FinalApp(){const[me,setMe]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('careflow_user'))}catch{return null}});const[page,setPage]=useState('home'),[notice,setNotice]=useState('');const done=user=>{sessionStorage.setItem('careflow_user',JSON.stringify(user));setMe(user);setPage('home')};const logout=()=>{sessionStorage.removeItem('careflow_token');sessionStorage.removeItem('careflow_user');setMe(null)};if(!me)return <Auth done={done}/>;const nav=me.role==='patient'?[['home','Home'],['book','Book visit'],['appointments','Appointments'],['records','Health records'],['reminders','Reminders'],['symptoms','AI navigator'],['report','Report analysis']]:me.role==='doctor'?[['home','Dashboard'],['appointments','Assigned patients'],['slots','Availability']]:[['home','Dashboard'],['approvals','Doctor approvals'],['departments','Departments'],['analytics','Analytics']];return <div className="app-shell"><aside><div className="brand"><I.HeartPulse/><span>CareFlow</span></div><div className="role-card"><div className="avatar">{me.fullName?.slice(0,2).toUpperCase()}</div><div><b>{me.fullName}</b><small>{me.role}</small></div></div><nav>{nav.map(([key,label])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}>{label}</button>)}</nav><button className="logout" onClick={logout}><I.LogOut size={18}/>Sign out</button></aside><main><header><div><p className="eyebrow">JWT SECURED · MONGODB ATLAS</p><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div></header><Screen me={me} page={page} say={setNotice}/>{notice&&<div className="toast"><I.CheckCircle2 size={18}/>{notice}</div>}</main></div>}

function Auth({done}){const[mode,setMode]=useState('login'),[role,setRole]=useState('patient'),[fullName,setName]=useState(''),[email,setEmail]=useState('patient@careflow.com'),[password,setPassword]=useState('patient123'),[specialty,setSpecialty]=useState('General Medicine'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);setError('');try{const body=mode==='register'?{fullName,email,password,role,specialty,fee:700}:{email,password};const data=await request(`/auth/${mode==='register'?'register':'login'}`,{method:'POST',body:JSON.stringify(body)});if(data.user.role!==role)throw new Error('Choose the role assigned to this account.');if(mode==='register'&&role==='doctor'){setMode('login');setError('Application submitted. An administrator must approve it before doctor access.');return}sessionStorage.setItem('careflow_token',data.token);done(data.user)}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="login"><section className="login-copy"><div className="brand"><I.HeartPulse/> CareFlow</div><div><p className="eyebrow">SMART HEALTHCARE PLATFORM</p><h1>Care that moves<br/>with your life.</h1><p>Secure appointments, records and care coordination.</p></div></section><section className="login-panel"><div className="login-card"><h2>{mode==='login'?'Welcome back':'Create account'}</h2><div className="roles">{(mode==='login'?['patient','doctor','admin']:['patient','doctor']).map(item=><button key={item} className={role===item?'selected':''} onClick={()=>setRole(item)}>{item}</button>)}</div>{mode==='register'&&<label>Full name<input value={fullName} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==='register'&&role==='doctor'&&<label>Specialty<input value={specialty} onChange={e=>setSpecialty(e.target.value)}/></label>}{error&&<p className="login-error">{error}</p>}<Button disabled={busy} onClick={submit}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</Button><button className="plain-link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create patient or doctor account':'Back to sign in'}</button><small className="demo">Demo: patient123 · doctor123 · admin123</small></div></section></div>}

function ReminderPopups(){useEffect(()=>{if(!('Notification' in window))return;const check=async()=>{try{const rows=await request('/reminders/mine'),now=new Date(),time=now.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:true}).replace(/^0/,''),today=now.toDateString();rows.filter(row=>String(row.reminderTime||'').replace(/^0/,'')===time).forEach(row=>{const key=`careflow-${row._id}-${today}`;if(!sessionStorage.getItem(key)&&Notification.permission==='granted'){sessionStorage.setItem(key,'1');new Notification('CareFlow medicine reminder',{body:`Time to take ${row.medicine} — ${row.dose||'as prescribed'}.`})}})}catch{}};if(Notification.permission==='default')Notification.requestPermission();check();const timer=setInterval(check,30000);return()=>clearInterval(timer)},[]);return null}
function Screen({me,page,say}){if(me.role==='patient')return <><ReminderPopups/><Patient me={me} page={page} say={say}/></>;if(me.role==='doctor')return <Doctor me={me} page={page} say={say}/>;return <Admin page={page} say={say}/>}
function Patient({me,page,say}){const[appointments,setAppointments]=useState([]);const load=()=>request('/appointments/mine').then(setAppointments).catch(e=>say(e.message));useEffect(load,[]);if(page==='book')return <Booking say={say} reload={load}/>;if(page==='appointments'||page==='home')return <Appointments rows={appointments} patient say={say} reload={load}/>;if(page==='records')return <Health patientId={me.id}/>;if(page==='reminders')return <Reminders/>;if(page==='symptoms')return <Symptoms/>;return <Report/>}
function Booking({say,reload}){const[docs,setDocs]=useState([]),[doctor,setDoctor]=useState(''),[slots,setSlots]=useState([]),[slot,setSlot]=useState(''),[emergency,setEmergency]=useState(false);useEffect(()=>{request('/doctors').then(x=>{setDocs(x);setDoctor(x[0]?.id||'')}).catch(e=>say(e.message))},[]);useEffect(()=>{if(doctor)request(`/doctors/${doctor}/slots`).then(setSlots).catch(e=>say(e.message))},[doctor]);const book=async()=>{try{const appt=await request('/appointments',{method:'POST',body:JSON.stringify({doctorId:doctor,slotId:slot,emergency})});say(`Booked. Predicted wait: ${appt.predictedWaitMinutes} minutes.`);setSlot('');reload()}catch(e){say(e.message)}};return <div className="form-page"><h3>Choose doctor</h3><select value={doctor} onChange={e=>setDoctor(e.target.value)}>{docs.map(d=><option value={d.id} key={d.id}>{d.name} · {d.specialty} · ₹{d.fee}</option>)}</select><h3>Available times</h3><div className="slots">{slots.map(s=><button key={s._id} className={slot===s._id?'slot-selected':''} onClick={()=>setSlot(s._id)}>{fmt(s.startsAt)}</button>)}</div><label className="emergency"><input type="checkbox" checked={emergency} onChange={e=>setEmergency(e.target.checked)}/>Priority emergency request</label><Button onClick={book}>Confirm booking</Button></div>}
function Appointments({rows,patient,say,reload}){return <div className="form-page"><div className="schedule-card">{rows.map(a=><div className="toggle-row" key={a._id}><div><b>{patient?a.doctor?.fullName:a.patient?.fullName}</b><small>{fmt(a.slot?.startsAt)} · {a.status} · wait {a.predictedWaitMinutes||0} min {a.emergency?'· Priority':''}</small></div>{patient&&a.status==='confirmed'?<button className="text-button" onClick={async()=>{try{await request(`/appointments/${a._id}/cancel`,{method:'PATCH'});say('Appointment cancelled');reload()}catch(e){say(e.message)}}}>Cancel</button>:null}</div>)}{!rows.length&&<div className="empty">No appointments yet.</div>}</div></div>}
function Health({patientId,doctorId}){const[records,setRecords]=useState([]),[prescriptions,setPrescriptions]=useState([]);useEffect(()=>{request(`/records/${patientId}`).then(setRecords);request(`/prescriptions/${patientId}`).then(setPrescriptions)},[patientId]);return <div className="form-page"><h3>Visit history</h3>{records.map(r=><div className="record" key={r._id}><div><b>{r.title}</b><small>{r.category} · {fmt(r.createdAt)}</small><span>{r.content}</span></div></div>)}<h3>Prescriptions</h3>{prescriptions.map(p=><div className="record" key={p._id}><div><b>{p.medicines.map(m=>m.name).join(', ')}</b><small>{p.medicines.map(m=>`${m.dose} · ${m.schedule}`).join(' | ')}</small><span>{p.notes}</span></div></div>)}</div>}
function Reminders(){const[rows,setRows]=useState([]);useEffect(()=>{request('/reminders/mine').then(setRows)},[]);return <div className="form-page">{rows.map(r=><div className="reminder" key={r._id}><div><b>{r.medicine}</b><span>{r.dose} · {r.reminderTime}</span></div></div>)}{!rows.length&&<div className="empty">No active reminders.</div>}</div>}
function Symptoms(){const[text,setText]=useState(''),[result,setResult]=useState('');return <div className="form-page symptom"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Describe symptoms in plain language"/><Button onClick={async()=>{try{setResult(await request('/symptoms/recommend',{method:'POST',body:JSON.stringify({symptoms:text})}))}catch(e){setResult({message:e.message})}}}>Find specialty</Button>{result&&<div className="result"><b>{result.recommendedSpecialty}</b><span>{result.message}</span><small>{result.disclaimer}</small></div>}</div>}
function Report(){const[text,setText]=useState(''),[result,setResult]=useState(null);return <div className="form-page symptom"><p className="intro">Paste report text for an informational summary. This does not diagnose.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste report text…"/><Button onClick={async()=>{try{setResult(await request('/reports/analyze',{method:'POST',body:JSON.stringify({reportText:text})}))}catch(e){setResult({summary:e.message})}}}>Analyze report</Button>{result&&<div className="result"><b>Summary</b><span>{result.summary}</span><ul>{result.questionsForClinician?.map(x=><li key={x}>{x}</li>)}</ul><small>{result.safetyNote}</small></div>}</div>}
function Doctor({me,page,say}){const[rows,setRows]=useState([]);const load=()=>request('/appointments/mine').then(setRows).catch(e=>say(e.message));useEffect(load,[]);if(page==='slots')return <Slots say={say}/>;return <><Appointments rows={rows}/><DoctorNotes rows={rows} say={say}/></>}
function Slots({say}){const[rows,setRows]=useState([]),[startsAt,setStartsAt]=useState('');const load=()=>request('/slots/mine').then(setRows).catch(e=>say(e.message));useEffect(load,[]);return <div className="form-page"><div className="inline-form"><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/><Button onClick={async()=>{try{await request('/slots',{method:'POST',body:JSON.stringify({startsAt})});setStartsAt('');load();say('Slot added')}catch(e){say(e.message)}}}>Add slot</Button></div><div className="schedule-card">{rows.map(s=><div className="toggle-row" key={s._id}><b>{fmt(s.startsAt)}</b><small>{s.booked?'Booked':'Available'}</small></div>)}</div></div>}
function DoctorNotes({rows,say}){const[patient,setPatient]=useState(''),[note,setNote]=useState(''),[medicine,setMedicine]=useState(''),[time,setTime]=useState('09:00 AM');const current=rows.find(x=>x.patient?._id===patient)||rows[0];useEffect(()=>{if(rows[0])setPatient(rows[0].patient._id)},[rows]);if(!current)return <div className="empty">No assigned patients yet.</div>;const save=async()=>{try{await request('/records',{method:'POST',body:JSON.stringify({patient:current.patient._id,category:'encounter',title:'Consultation note',content:note})});await request('/prescriptions',{method:'POST',body:JSON.stringify({patient:current.patient._id,medicines:[{name:medicine,dose:'As prescribed',schedule:time}],notes:note})});say('Note, prescription and reminder saved.');setNote('');setMedicine('')}catch(e){say(e.message)}};return <div className="form-page"><h3>Add consultation outcome for {current.patient.fullName}</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Consultation note"/><div className="inline-form"><input value={medicine} onChange={e=>setMedicine(e.target.value)} placeholder="Tablet / medicine"/><input value={time} onChange={e=>setTime(e.target.value)} placeholder="Time"/></div><Button disabled={!note||!medicine} onClick={save}>Save prescription</Button></div>}
function Admin({page,say}){if(page==='approvals')return <Approvals say={say}/>;if(page==='departments')return <Departments say={say}/>;return <Analytics/>}
function Approvals({say}){const[rows,setRows]=useState([]);const load=()=>request('/admin/pending-doctors').then(setRows).catch(e=>say(e.message));useEffect(load,[]);return <div className="form-page">{rows.map(x=><div className="approval" key={x._id}><div><b>{x.user.fullName} · {x.specialty}</b><span>{x.user.email} · ₹{x.fee}</span></div><Button onClick={async()=>{try{await request(`/admin/doctors/${x.user._id}`,{method:'PATCH',body:JSON.stringify({approved:true})});load();say('Doctor approved')}catch(e){say(e.message)}}}>Approve</Button></div>)}{!rows.length&&<div className="empty">All registrations reviewed.</div>}</div>}
function Departments({say}){const[rows,setRows]=useState([]),[name,setName]=useState('');const load=()=>request('/departments').then(setRows).catch(e=>say(e.message));useEffect(load,[]);return <div className="form-page"><div className="schedule-card">{rows.map(x=><div className="toggle-row" key={x._id}><b>{x.name}</b></div>)}</div><div className="inline-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Department"/><Button onClick={async()=>{try{await request('/departments',{method:'POST',body:JSON.stringify({name})});setName('');load()}catch(e){say(e.message)}}}>Add</Button></div></div>}
function Analytics(){const[data,setData]=useState(null);useEffect(()=>{request('/admin/analytics').then(setData)},[]);if(!data)return <div className="empty">Loading analytics…</div>;const days=data.appointmentsByDay||[];return <><div className="stat-grid"><div className="stat"><b>{data.patients}</b><span>Patients</span></div><div className="stat"><b>{data.doctors}</b><span>Doctors</span></div><div className="stat"><b>{data.appointments}</b><span>Appointments</span></div><div className="stat"><b>{data.pendingDoctors}</b><span>Pending doctors</span></div></div><div className="chart-canvas"><Bar data={{labels:days.map(x=>x._id),datasets:[{label:'Appointments',data:days.map(x=>x.count),backgroundColor:'#0f9d92'}]}} options={{responsive:true,maintainAspectRatio:false}}/></div></>}
